In [90]:
import pandas as pd
import altair as alt

df = pd.read_csv('source/homeless.csv')
df.head()

,ITTER107,Territorio,TIPO_DATO_CENS_POP,Tipo dato,SEXISTAT1,Sesso,ETA1,Classe di età,CITTADINANZA,Cittadinanza,TIME,Seleziona periodo,Value,Flag Codes,Flags
0,IT,Italia,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,M,maschi,TOTAL,totale,ITL,italiano-a,2021,2021,39131,NaN,NaN
1,IT,Italia,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,F,femmine,TOTAL,totale,ITL,italiano-a,2021,2021,20742,NaN,NaN
2,IT,Italia,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,T,totale,TOTAL,totale,ITL,italiano-a,2021,2021,59873,NaN,NaN
3,ITC,Nord-ovest,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,M,maschi,TOTAL,totale,ITL,italiano-a,2021,2021,12357,NaN,NaN
4,ITC,Nord-ovest,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,F,femmine,TOTAL,totale,ITL,italiano-a,2021,2021,6043,NaN,NaN

In [91]:
df = df[df['ITTER107'] == 'ITC10'].reset_index()

In [92]:
df

Empty DataFrame
Columns: [index, ITTER107, Territorio, TIPO_DATO_CENS_POP, Tipo dato, SEXISTAT1, Sesso, ETA1, Classe di età, CITTADINANZA, Cittadinanza, TIME, Seleziona periodo, Value, Flag Codes, Flags]
Index: []

In [85]:
df = df[df['ITTER107'] == 'IT'].reset_index()

In [14]:
from pandas_profiling import ProfileReport
prof = ProfileReport(df)
prof.to_file(output_file='output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [15]:
df.columns

Index(['df_index', 'ITTER107', 'Territorio', 'TIPO_DATO_CENS_POP', 'Tipo dato',
       'SEXISTAT1', 'Sesso', 'ETA1', 'Classe di età', 'CITTADINANZA',
       'Cittadinanza', 'TIME', 'Seleziona periodo', 'Value', 'Flag Codes',
       'Flags'],
      dtype='object')

In [16]:
df = df[['SEXISTAT1', 'ETA1', 'CITTADINANZA', 'Value']]
df.head()

  SEXISTAT1   ETA1 CITTADINANZA  Value
0         M  TOTAL          ITL  39131
1         F  TOTAL          ITL  20742
2         T  TOTAL          ITL  59873
3         M  TOTAL       FRGAPO  26276
4         F  TOTAL       FRGAPO  10048

In [20]:
df = df.rename(columns={'SEXISTAT1' : 'Gender', 'ETA1' : 'Age', 'CITTADINANZA' : 'Citizenship'})

In [21]:
df.head()

  Gender    Age Citizenship  Value
0      M  TOTAL         ITL  39131
1      F  TOTAL         ITL  20742
2      T  TOTAL         ITL  59873
3      M  TOTAL      FRGAPO  26276
4      F  TOTAL      FRGAPO  10048

In [25]:
alt.Chart(df[df['Gender'] != 'T']).mark_bar().encode(
    x = alt.X('Gender'),
    y = alt.Y('Value')
).properties(width=300)

alt.Chart(...)

In [36]:
alt.Chart(df[(df['Gender'] == 'T') & (df['Age'] != 'TOTAL')]).mark_bar().encode(
    x = alt.X('Age', sort=['Y_UN17', 'Y18-34', 'Y35-54', 'Y_GE55']),
    y = alt.Y('Value')
).properties(width=300)

alt.Chart(...)

In [43]:
alt.Chart(df[(df['Gender'] != 'T') & (df['Age'] != 'TOTAL')]).mark_bar().encode(
    x = alt.X('Age', sort=['Y_UN17', 'Y18-34', 'Y35-54', 'Y_GE55']),
    y = alt.Y('Value'),
    color=alt.Color('Gender')
).properties(width=300)

alt.Chart(...)

In [41]:
alt.Chart(df[(df['Gender'] != 'T') & (df['Age'] == 'TOTAL') & (df['Citizenship'] != 'TOTAL')]).mark_bar().encode(
    x = alt.X('Citizenship'),
    y = alt.Y('Value'),
    color=alt.Color('Gender')
).properties(width=300)

alt.Chart(...)

In [109]:
df2 = pd.read_csv('source/population.csv')
df2.head()

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,SEX,AGE,MARITAL_STATUS,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_SEX,NOTE_AGE,NOTE_MARITAL_STATUS,BASE_PER,UNIT_MEAS,UNIT_MULT
0,IT1:22_289_DF_DCIS_POPRES1_1(1.0),A,IT,JAN,1,TOTAL,1,2019,13605095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT1:22_289_DF_DCIS_POPRES1_1(1.0),A,IT,JAN,1,TOTAL,1,2020,13630443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT1:22_289_DF_DCIS_POPRES1_1(1.0),A,IT,JAN,1,TOTAL,1,2021,13628057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IT1:22_289_DF_DCIS_POPRES1_1(1.0),A,IT,JAN,1,TOTAL,1,2022,13683804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IT1:22_289_DF_DCIS_POPRES1_1(1.0),A,IT,JAN,1,TOTAL,15,2019,12016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
df2 = df2[df2['TIME_PERIOD'] == 2021]

In [111]:
len(df2)

293454

In [112]:
df2.REF_AREA.unique()

array(['IT', 'IT108', 'IT109', 'IT110', 'IT111', 'ITC', 'ITC1', 'ITC11',
       'ITC12', 'ITC13', 'ITC14', 'ITC15', 'ITC16', 'ITC17', 'ITC18',
       'ITC2', 'ITC20', 'ITC3', 'ITC31', 'ITC32', 'ITC33', 'ITC34',
       'ITC4', 'ITC41', 'ITC42', 'ITC43', 'ITC44', 'ITC45', 'ITC46',
       'ITC47', 'ITC48', 'ITC49', 'ITC4A', 'ITC4B', 'ITCD', 'ITD', 'ITD1',
       'ITD10', 'ITD2', 'ITD20', 'ITD3', 'ITD31', 'ITD32', 'ITD33',
       'ITD34', 'ITD35', 'ITD36', 'ITD37', 'ITD4', 'ITD41', 'ITD42',
       'ITD43', 'ITD44', 'ITD5', 'ITD51', 'ITD52', 'ITD53', 'ITD54',
       'ITD55', 'ITD56', 'ITD57', 'ITD58', 'ITD59', 'ITDA', 'ITE', 'ITE1',
       'ITE11', 'ITE12', 'ITE13', 'ITE14', 'ITE15', 'ITE16', 'ITE17',
       'ITE18', 'ITE19', 'ITE1A', 'ITE2', 'ITE21', 'ITE22', 'ITE3',
       'ITE31', 'ITE32', 'ITE33', 'ITE34', 'ITE4', 'ITE41', 'ITE42',
       'ITE43', 'ITE44', 'ITE45', 'ITF', 'ITF1', 'ITF11', 'ITF12',
       'ITF13', 'ITF14', 'ITF2', 'ITF21', 'ITF22', 'ITF3', 'ITF31',
       'ITF32', 'ITF33', 'ITF34', 'ITF35', 'ITF4', 'ITF41', 'ITF42',
       'ITF43', 'ITF44', 'ITF45', 'ITF5', 'ITF51', 'ITF52', 'ITF6',
       'ITF61', 'ITF62', 'ITF63', 'ITF64', 'ITF65', 'ITFG', 'ITG', 'ITG1',
       'ITG11', 'ITG12', 'ITG13', 'ITG14', 'ITG15', 'ITG16', 'ITG17',
       'ITG18', 'ITG19', 'ITG2', 'ITG25', 'ITG26', 'ITG27', 'ITG28'],
      dtype=object)

In [62]:
['Y_UN17', 'Y18-34', 'Y35-54', 'Y_GE55']

group_ages = {'Y_UN17' : [0,18],
              'Y18-34' : [18, 35],
              'Y35-54' : [35,55],
              'Y_GE55' : [55,150]}

data = {}

for k,v in group_ages.items():
    
    ranges = []
    for i in range(v[0],v[1]):
        ranges.append(f"Y{i}")
        
    data[k] = df2[df2['AGE'].isin(ranges)]['AGE'].count()
    
    if k == 'Y_GE55':
        data[k] += df2[df2['AGE'] == 'Y_GE100']['AGE'].count()
        
        
    
data

{'Y_UN17': 17262, 'Y18-34': 55896, 'Y35-54': 65760, 'Y_GE55': 151248}

In [63]:
total = 0
for k,v in data.items():
    total += v
    
total

290166

In [65]:
len(df2) - len(df2[df2['AGE'] == 'TOTAL'])

290166

In [72]:
df3 = pd.DataFrame.from_dict(data,orient='index').reset_index()

df3.rename(columns={'index' : 'AGE', 0 : 'Value'}, inplace=True)
df3

      AGE   Value
0  Y_UN17   17262
1  Y18-34   55896
2  Y35-54   65760
3  Y_GE55  151248

In [201]:
df4 = pd.read_csv('source/homeless_by_regions_2021.csv', sep=';')
df4

,ITTER107,Territorio,TIPO_DATO_CENS_POP,Tipo dato,SEXISTAT1,Sesso,ETA1,Classe di età,CITTADINANZA,Cittadinanza,TIME,Seleziona periodo,Value,Flag Codes,Flags
0,ITC1,Piemonte,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,M,maschi,TOTAL,totale,ITL,italiano-a,2021,2021,4218,NaN,NaN
1,ITC1,Piemonte,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,F,femmine,TOTAL,totale,ITL,italiano-a,2021,2021,1496,NaN,NaN
2,ITC1,Piemonte,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,T,totale,TOTAL,totale,ITL,italiano-a,2021,2021,5714,NaN,NaN
3,ITC2,Valle d'Aosta / Vallée d'Aoste,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,M,maschi,TOTAL,totale,ITL,italiano-a,2021,2021,41,NaN,NaN
4,ITC2,Valle d'Aosta / Vallée d'Aoste,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,F,femmine,TOTAL,totale,ITL,italiano-a,2021,2021,17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,ITE1,Toscana,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,F,femmine,Y_GE55,55 anni e più,FRGAPO,straniero-a/apolide,2021,2021,79,NaN,NaN
973,ITD4,Friuli-Venezia Giulia,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,T,totale,Y_GE55,55 anni e più,FRGAPO,straniero-a/apolide,2021,2021,45,NaN,NaN
974,ITC2,Valle d'Aosta / Vallée d'Aoste,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,F,femmine,Y35-54,35-54 anni,FRGAPO,straniero-a/apolide,2021,2021,1,NaN,NaN
975,ITD5,Emilia-Romagna,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,M,maschi,Y35-54,35-54 anni,FRGAPO,straniero-a/apolide,2021,2021,466,NaN,NaN
976,ITE2,Umbria,PR_SEC_HOMELESS_PERS,persone senza tetto e senza fissa dimora,M,maschi,Y_GE55,55 anni e più,TOTAL,totale,2021,2021,107,NaN,NaN

In [202]:
df4 = df4[['ITTER107','Territorio','SEXISTAT1', 'ETA1', 'CITTADINANZA', 'Value']]

In [203]:
df4.CITTADINANZA.unique()

array(['ITL', 'FRGAPO', 'TOTAL'], dtype=object)

In [204]:
df4_tot = df4[(df4['ETA1'] == 'TOTAL') & (df4['SEXISTAT1'] == 'T') &  (df4['CITTADINANZA'] == 'TOTAL')]

In [205]:
df4_tot['Territorio'].unique()

df4_tot['Territorio'] = df4_tot['Territorio'].str.replace('Trentino Alto Adige / Südtirol', 'Trentino-Alto Adige/Südtirol')

/var/folders/yc/q002jxmj3lb5jz2p9nrxyt840000gn/T/ipykernel_96039/493343816.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4_tot['Territorio'] = df4_tot['Territorio'].str.replace('Trentino Alto Adige / Südtirol', 'Trentino-Alto Adige/Südtirol')

In [206]:
# Load the TopoJSON file by URL
url = "https://raw.githubusercontent.com/openpolis/geojson-italy/master/topojson/limits_IT_regions.topo.json"


source = alt.topo_feature(url, "regions")

alt.Chart(source).mark_geoshape().encode(
    tooltip='properties.reg_name:N',
    color=alt.Color('Value:Q',scale=alt.Scale(range=['#075630', '#A4D333','#FCE135',  '#FEB41D','#DB7222']))
).project('mercator').properties(
    width=500,
    height=300
).transform_lookup(
    lookup='properties.reg_name',
    from_=alt.LookupData(df4_tot, 'Territorio', ['Territorio', 'Value'])
).properties(title='Homeless in Italy in 2021')

/Users/angelica/Library/Python/3.8/lib/python/site-packages/altair/utils/core.py:317: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col_name, dtype in df.dtypes.iteritems():

alt.Chart(...)

In [207]:
df4_tot

,ITTER107,Territorio,SEXISTAT1,ETA1,CITTADINANZA,Value
128,ITC1,Piemonte,T,TOTAL,TOTAL,8766
131,ITC2,Valle d'Aosta / Vallée d'Aoste,T,TOTAL,TOTAL,73
134,ITC3,Liguria,T,TOTAL,TOTAL,4293
137,ITC4,Lombardia,T,TOTAL,TOTAL,16346
140,ITDA,Trentino-Alto Adige/Südtirol,T,TOTAL,TOTAL,612
143,ITD1,Provincia Autonoma Bolzano / Bozen,T,TOTAL,TOTAL,313
146,ITD2,Provincia Autonoma Trento,T,TOTAL,TOTAL,299
149,ITD3,Veneto,T,TOTAL,TOTAL,3794
152,ITD4,Friuli-Venezia Giulia,T,TOTAL,TOTAL,1451
155,ITD5,Emilia-Romagna,T,TOTAL,TOTAL,4926
158,ITE1,Toscana,T,TOTAL,TOTAL,4450
161,ITE2,Umbria,T,TOTAL,TOTAL,431
164,ITE3,Marche,T,TOTAL,TOTAL,1107
167,ITE4,Lazio,T,TOTAL,TOTAL,24049
170,ITF1,Abruzzo,T,TOTAL,TOTAL,610
173,ITF2,Molise,T,TOTAL,TOTAL,101
176,ITF3,Campania,T,TOTAL,TOTAL,7828
179,ITF4,Puglia,T,TOTAL,TOTAL,7655
182,ITF5,Basilicata,T,TOTAL,TOTAL,119
185,ITF6,Calabria,T,TOTAL,TOTAL,2351
188,ITG1,Sicilia,T,TOTAL,TOTAL,4023
191,ITG2,Sardegna,T,TOTAL,TOTAL,3212

In [208]:
df5 = pd.read_csv('source/population_by_regions_2021.csv')
df5

,ITTER107,Territorio,TIPO_DATO_CENS_POP,Tipo dato,SEXISTAT1,Sesso,ETA1,Classe di età,TIME,Seleziona periodo,Value,Flag Codes,Flags
0,ITD4,Friuli-Venezia Giulia,RESPOP_AV,popolazione residente,M,maschi,Y_UN4,fino a 4 anni,2021,2021,19794,NaN,NaN
1,ITE1,Toscana,RESPOP_AV,popolazione residente,M,maschi,Y_UN4,fino a 4 anni,2021,2021,61789,NaN,NaN
2,ITF6,Calabria,RESPOP_AV,popolazione residente,M,maschi,Y_UN4,fino a 4 anni,2021,2021,36842,NaN,NaN
3,ITD2,Provincia Autonoma Trento,RESPOP_AV,popolazione residente,T,totale,Y5-9,5-9 anni,2021,2021,25101,NaN,NaN
4,ITD3,Veneto,RESPOP_AV,popolazione residente,M,maschi,Y5-9,5-9 anni,2021,2021,105344,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1447,ITDA,Trentino Alto Adige / Südtirol,RESPOP_AV,popolazione residente,F,femmine,Y30-34,30-34 anni,2021,2021,29518,NaN,NaN
1448,ITDA,Trentino Alto Adige / Südtirol,RESPOP_AV,popolazione residente,T,totale,Y20-24,20-24 anni,2021,2021,59099,NaN,NaN
1449,ITDA,Trentino Alto Adige / Südtirol,RESPOP_AV,popolazione residente,M,maschi,Y70-74,70-74 anni,2021,2021,25405,NaN,NaN
1450,ITDA,Trentino Alto Adige / Südtirol,RESPOP_AV,popolazione residente,M,maschi,Y80-84,80-84 anni,2021,2021,15882,NaN,NaN
1451,ITDA,Trentino Alto Adige / Südtirol,RESPOP_AV,popolazione residente,F,femmine,Y50-54,50-54 anni,2021,2021,42905,NaN,NaN

In [209]:
df5_tot = df5[(df5['ETA1'] == 'TOTAL') & (df5['Sesso'] == 'totale')]
df5_tot['Territorio'] = df5_tot['Territorio'].str.replace('Trentino Alto Adige / Südtirol', 'Trentino-Alto Adige/Südtirol')

/var/folders/yc/q002jxmj3lb5jz2p9nrxyt840000gn/T/ipykernel_96039/2890083438.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5_tot['Territorio'] = df5_tot['Territorio'].str.replace('Trentino Alto Adige / Südtirol', 'Trentino-Alto Adige/Südtirol')

In [210]:
len(df5_tot), len(df4_tot)

(22, 22)

In [211]:
df5_tot.columns

Index(['ITTER107', 'Territorio', 'TIPO_DATO_CENS_POP', 'Tipo dato',
       'SEXISTAT1', 'Sesso', 'ETA1', 'Classe di età', 'TIME',
       'Seleziona periodo', 'Value', 'Flag Codes', 'Flags'],
      dtype='object')

In [212]:
df5_tot = df5_tot[['Value', 'ITTER107']]
df4_tot = df4_tot[['Value', 'ITTER107','Territorio']]

In [213]:
df6 = df5_tot.set_index('ITTER107').join(df4_tot.set_index('ITTER107'),lsuffix='_pop', rsuffix='_hom').reset_index()

In [214]:
df6['Ratio'] = df6['Value_hom']/df6['Value_pop']

In [215]:
# Load the TopoJSON file by URL
url = "https://raw.githubusercontent.com/openpolis/geojson-italy/master/topojson/limits_IT_regions.topo.json"


source = alt.topo_feature(url, "regions")

alt.Chart(source).mark_geoshape().encode(
    tooltip='properties.reg_name:N',
    color=alt.Color('Ratio:Q')
).project('mercator').properties(
    width=500,
    height=500
).transform_lookup(
    lookup='properties.reg_name',
    from_=alt.LookupData(df6, 'Territorio', ['Territorio', 'Ratio'])
).properties(title='Homeless in Italy in 2021')

/Users/angelica/Library/Python/3.8/lib/python/site-packages/altair/utils/core.py:317: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col_name, dtype in df.dtypes.iteritems():

alt.Chart(...)

In [219]:
df6

,ITTER107,Value_pop,Value_hom,Territorio,Ratio
0,ITF4,3922941,7655,Puglia,0.001951
1,ITD2,540958,299,Provincia Autonoma Trento,0.000553
2,ITF3,5624420,7828,Campania,0.001392
3,ITE4,5714882,24049,Lazio,0.004208
4,ITC3,1509227,4293,Liguria,0.002845
5,ITE2,858812,431,Umbria,0.000502
6,ITF5,541168,119,Basilicata,0.000220
7,ITE1,3663191,4450,Toscana,0.001215
8,ITD5,4425366,4926,Emilia-Romagna,0.001113
9,ITD3,4847745,3794,Veneto,0.000783
10,ITF2,292150,101,Molise,0.000346
11,ITD1,532616,313,Provincia Autonoma Bolzano / Bozen,0.000588
12,ITC4,9943004,16346,Lombardia,0.001644
13,ITF1,1275950,610,Abruzzo,0.000478
14,ITF6,1855454,2351,Calabria,0.001267
15,ITG1,4833329,4023,Sicilia,0.000832
16,ITG2,1587413,3212,Sardegna,0.002023
17,ITC1,4256350,8766,Piemonte,0.002060
18,ITE3,1487150,1107,Marche,0.000744
19,ITC2,123360,73,Valle d'Aosta / Vallée d'Aoste,0.000592
20,ITD4,1194647,1451,Friuli-Venezia Giulia,0.001215
21,ITDA,1073574,612,Trentino-Alto Adige/Südtirol,0.000570

In [221]:
df6.drop(labels=[11,1], axis=0,inplace=True)

In [222]:
alt.Chart(df6).mark_bar().encode(
    y = alt.Y('Territorio', sort='-x'),
    x = alt.X('Ratio'),
   
).properties(width=500)

/Users/angelica/Library/Python/3.8/lib/python/site-packages/altair/utils/core.py:317: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col_name, dtype in df.dtypes.iteritems():

alt.Chart(...)

In [223]:
alt.Chart(df4_tot).mark_bar().encode(
    y = alt.Y('Territorio', sort='-x'),
    x = alt.X('Value'),
   
).properties(width=500)

alt.Chart(...)